spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.254.129:3306/gmall?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
      password: 123456
      username: root


#mybatis-plus:
  #configuration:
    #map-underscore-to-camel-case: false
  #mapper-locations: classpath:mapper/*.xml



dubbo:
  application:
    name: manage-service
  registry:
    address: zookeeper://192.168.254.129:2181
  protocol:
    name: dubbo
    port: 20880
logging:
  level: 
    com.timain.mapper: debug
